seed: 123
num_gpus: 1
num_epochs: 5

resume_dir: /cluster/52/sarwath/snet/output/models/ # /cluster/51/soniacp/semantic/models/ #
print_interval: 10


solver:
  method: adam
  lr:  0.0001  # 0.00001 #   
  weight_decay: 0.00001 # 0 #  

dataset:
  root_dir: output_dir/processed/
  batch_size: 16
  num_workers: 8
  shuffle: False

model:
  arch:  resnet101 # dpt # 
  pretrained: True
  embed_dims: 2
  fix_bn: False
  semantic: False
  num_samples: 20
  embedding_loss: contrastive_anchors_neg # [hinge, contrastive_centers, contrastive_anchors, contrastive_anchors_neg]
  extra_semantic_layers: False

