seed: 123
num_gpus: 1
num_epochs: 5
resume_dir: /cluster/52/sarwath/snet/output/models/
print_interval: 100


solver:
  method: adam
  lr: 0.0001
  weight_decay: 0.00001

dataset:
  root_dir: /cluster/52/sarwath/snet/output/processed/
  batch_size: 16
  num_workers: 8

model:
  arch: resnet101
  pretrained: True
  embed_dims: 2
  fix_bn: False
  name: baseline_4
  dpt: False
  semantic: False
